"""
Unit tests for Day 7 solution.
"""

import os
import unittest
from textwrap import dedent

from solution import parse_input, part1, part2  # noqa: F401


class TestSolution(unittest.TestCase):
    """Test cases for Day 7 solution."""

    def setUp(self):
        """Set up test fixtures."""
        self.maxDiff = None
        self.test_file = "test_input.txt"

    def tearDown(self):
        """Clean up test files."""
        if os.path.exists(self.test_file):
            os.remove(self.test_file)

    def test_part1_example(self):
        """Test Part 1 with example input - should return 21 splits."""
        with open(self.test_file, "w") as f:
            f.write(
                dedent(
                    """\
                    .......S.......
                    ...............
                    .......^.......
                    ...............
                    ......^.^......
                    ...............
                    .....^.^.^.....
                    ...............
                    ....^.^...^....
                    ...............
                    ...^.^...^.^...
                    ...............
                    ..^...^.....^..
                    ...............
                    .^.^.^.^.^...^.
                    ...............
                    """
                )
            )

        result = part1(self.test_file)
        self.assertEqual(result, 21, "Example should have 21 splits")

    def test_part2_example(self):
        """Test Part 2 with example input - should return 40 timelines."""
        with open(self.test_file, "w") as f:
            f.write(
                dedent(
                    """\
                    .......S.......
                    ...............
                    .......^.......
                    ...............
                    ......^.^......
                    ...............
                    .....^.^.^.....
                    ...............
                    ....^.^...^....
                    ...............
                    ...^.^...^.^...
                    ...............
                    ..^...^.....^..
                    ...............
                    .^.^.^.^.^...^.
                    ...............
                    """
                )
            )

        result = part2(self.test_file)
        self.assertEqual(result, 40, "Example should have 40 timelines")


def run_tests():
    """Run all tests and return success status."""
    print("Running unit tests...")
    test_suite = unittest.TestLoader().loadTestsFromTestCase(TestSolution)
    result = unittest.TextTestRunner(verbosity=2).run(test_suite)
    return result.wasSuccessful()


if __name__ == "__main__":
    run_tests()
